### ISSUE TITLE
depth map error with FP16, but it works with fp32: "compute_indices_weights_linear" not implemented for 'Half' 

### ISSUE THREAD

**Issue by AugmentedRealityCat** [kijai/ComfyUI-Geowizard#1]
If you take the depth output from a Geowizard node and plug it into an `Image Upscale` or `Image Upscale By` node it will work well if you have loaded the FP32 version of Geowizard, but will stop and give an error messages if you use the FP16 version of Geowizard instead.

All in all, this might not be a bug with the Geowizard node itself, but with other nodes that are not compatible with the images it is outputting (see "My Guess" below). 

The error message is linked to the upscaling algorithm you select. Here are a few examples:

When using **bilinear**:
`"compute_indices_weights_linear" not implemented for 'Half'`

When using **neares-exact**:
`"compute_indices_weights_nearest" not implemented for 'Half'`

when using **area**:
`"adaptive_avg_pool2d" not implemented for 'Half'`

when using **bicubic**:
`"compute_indices_weights_cubic" not implemented for 'Half'`

IMPORTANT: **when using Lanczos, everything works**, even in FP16
IMPORTANT: **when using FP32, it works in all modes**
IMPORTANT: when using the **normal map output** (but not the depth output) it **works with all nodes, both in FP16 and in FP32**
IMPORTANT: it **works when using different upscaling nodes** (but not with _Image Upscale_ nor with _Image Upscale By_)

MY GUESS: since the problem comes from images that the GeoWizard node is outputting, and not the node itself, and that it only applies to depthmaps, **my guess is that GeoWizard is outputting depthmaps in 16 bit greyscale** instead of 8 bit per channel RGB. This would explain why it works with the "resize image" nodes, but not with the "upscale image" nodes, one being theoretically compatible with both 16 bpc and 8 bpc, while "upscale image" only seems to suppoer 8 bpc images.

Here is an example of a full error message - this is the one I got when trying _bilinear_ :

```
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1621, in upscale
    s = comfy.utils.common_upscale(samples, width, height, upscale_method, "disabled")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 422, in common_upscale
    return torch.nn.functional.interpolate(s, size=(height, width), mode=upscale_method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\functional.py", line 4020, in interpolate
    return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "compute_indices_weights_linear" not implemented for 'Half'
```

Parting notes: is there a list somewhere of all the nodes that can work with images in 16 bit greyscale (or 16 bpc RGB) format ?

**Comment by kijai** [comment]
Yeah the node should return the images in float32, just forgot to add that, should be fixed now.

**Comment by AugmentedRealityCat** [comment]
I confirm that the problem is fixed now. Thanks !

Like Colombo would say just before leaving, "Just one more thing": is it normal that the depthmap output from FP16 is slightly different from the one you get in FP32 ? If it should not, let me know and I'll document the problem for you.

**Comment by HsinYiMax** [comment]
> I confirm that the problem is fixed now. Thanks !
> 
> Like Colombo would say just before leaving, "Just one more thing": is it normal that the depthmap output from FP16 is slightly different from the one you get in FP32 ? If it should not, let me know and I'll document the problem for you.

Hello, I also encountered the same problem. I updated all the nodes and the problem still occurred. How did you solve it in the end? Please tell me, thank you!
